# Generated by Django 5.0.1 on 2024-02-14 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='No title provided', max_length=255)),
                ('description', models.TextField(default='No description provided')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('presentation_date', models.DateField(default=django.utils.timezone.now)),
                ('case_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Appealed', 'Appealed')], default='Open', max_length=255)),
                ('case_outcome', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=255)),
                ('case_verdict', models.CharField(choices=[('Pending', 'Pending'), ('Guilty', 'Guilty'), ('Not Guilty', 'Not Guilty'), ('Dismissed', 'Dismissed'), ('Settled', 'Settled')], default='Pending', max_length=255)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='No type provided', max_length=255)),
                ('description', models.TextField(default='No description provided')),
                ('is_analyzed', models.BooleanField(default=False)),
                ('is_collected', models.BooleanField(default=False)),
                ('is_presented', models.BooleanField(default=False)),
                ('is_disposed', models.BooleanField(default=False)),
                ('collected_on', models.DateField(default=django.utils.timezone.now)),
                ('collection_details', models.TextField(default='No details provided')),
                ('analysed_on', models.DateField(blank=True, null=True)),
                ('analysis_details', models.TextField(blank=True, null=True)),
                ('presented_on', models.DateField(blank=True, null=True)),
                ('presentation_details', models.TextField(blank=True, null=True)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('disposal_details', models.TextField(blank=True, null=True)),
                ('disposal_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('disposal_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidences',
                'ordering': ['case'],
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name provided', max_length=255)),
                ('phone_number', models.CharField(default='No contact provided', max_length=20)),
                ('email', models.EmailField(default='No email provided', max_length=255)),
                ('statement', models.TextField(default='No statement provided')),
                ('relationship_to_victim', models.CharField(default='No relationship provided', max_length=255)),
            ],
            options={
                'verbose_name': 'Victim',
                'verbose_name_plural': 'Victims',
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name provided', max_length=255)),
                ('phone_number', models.CharField(default='No contact provided', max_length=20)),
                ('email', models.EmailField(default='No email provided', max_length=255)),
                ('statement', models.TextField(default='No statement provided')),
            ],
            options={
                'verbose_name': 'Victim',
                'verbose_name_plural': 'Victims',
            },
        ),
    ]
