# Generated by Django 5.0.1 on 2024-02-14 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='officer',
            new_name='case_officer',
        ),
        migrations.RemoveField(
            model_name='case',
            name='presentation_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='case',
            name='victim',
        ),
        migrations.AddField(
            model_name='reporter',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporters', to='case_management_app.case'),
        ),
        migrations.AddField(
            model_name='victim',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='case_management_app.case'),
        ),
    ]
