# Generated by Django 5.0.1 on 2024-02-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management_app', '0004_rename_description_case_case_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='email',
            new_name='reporter_email',
        ),
        migrations.RenameField(
            model_name='reporter',
            old_name='name',
            new_name='reporter_name',
        ),
        migrations.RenameField(
            model_name='reporter',
            old_name='phone_number',
            new_name='reporter_phone_number',
        ),
        migrations.RenameField(
            model_name='reporter',
            old_name='statement',
            new_name='reporter_statement',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='email',
            new_name='victim_email',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='name',
            new_name='victim_name',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='phone_number',
            new_name='victim_phone_number',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='statement',
            new_name='victim_statement',
        ),
    ]
