# Generated by Django 5.0.1 on 2024-02-14 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management_app', '0005_rename_email_reporter_reporter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_outcome',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Appealed', 'Appealed')], default='Open', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_verdict',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Guilty', 'Guilty'), ('Not Guilty', 'Not Guilty'), ('Dismissed', 'Dismissed'), ('Settled', 'Settled')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
