# Generated by Django 5.0.2 on 2024-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management_app', '0008_evidence_disposed_alter_evidence_disposed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='disposed',
            field=models.BooleanField(default=False),
        ),
    ]
