# Generated by Django 5.0.2 on 2024-03-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management_app', '0009_case_disposed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='case',
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_name', models.CharField(default='No name provided', max_length=255)),
                ('complainant_phone_number', models.CharField(default='No contact provided', max_length=20)),
                ('complainant_email', models.EmailField(default='No email provided', max_length=255)),
                ('complainant_statement', models.TextField(default='No statement provided')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainants', to='case_management_app.case')),
            ],
            options={
                'verbose_name': 'Complainant',
                'verbose_name_plural': 'Complainants',
            },
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
        migrations.DeleteModel(
            name='Victim',
        ),
    ]
